import type { Metadata } from "next";
import Link from "next/link";
import { shopProducts } from "@/lib/shop";
import { resolveShopOffer } from "@/lib/shop-offers";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Commercial disclosure", description: "How Starlight Technology handles affiliate links, samples, sponsorship and editorial independence.", alternates: { canonical: "/disclosure" } };

export default function DisclosurePage() {
  const affiliateCount = shopProducts.filter((product) => resolveShopOffer(product).relationship === "affiliate").length;
  return <article className="article shell"><header className="article-header"><p className="eyebrow">Commercial disclosure</p><h1>The verdict is not for sale.</h1><p className="article-summary">Starlight Technology may earn revenue from advisory work and clearly labelled affiliate links. Commercial relationships never change evidence status or remove wrong-purchase conditions.</p></header><section className="article-section"><h2>Current shop status</h2><p>{affiliateCount > 0 ? `${affiliateCount} approved affiliate ${affiliateCount === 1 ? "destination is" : "destinations are"} active in the Studio Shop. We may earn a commission when you purchase through those links.` : "The Studio Shop currently links to official manufacturer sources. No affiliate destinations are active, and those ordinary links earn Starlight no commission."}</p><p>Hardware checkout happens on the linked site. Starlight does not accept hardware orders in this release. There are no sponsored placements or vendor-provided review units represented as independent tests.</p><Link href="/shop">Browse the Studio Shop →</Link></section><section className="article-section"><h2>Commercial link policy</h2><ul><li>Commission disclosure appears beside each active affiliate link.</li><li>Partner-issued destinations stay intact and use sponsored link qualification.</li><li>Affiliate links require an approval record, an allowed destination and an unexpired verification period.</li><li>Price and stock require an authorised, dated merchant source; this catalog displays neither.</li><li>Alternatives remain visible regardless of commission.</li><li>Samples and sponsored access are disclosed on the relevant page.</li></ul></section><section className="article-section"><h2>Evidence and prospective partners</h2><p>Product pages separate manufacturer documentation from Starlight’s buying inference. They do not claim hands-on testing. A brand listed in the shop or partner directory does not imply a reseller appointment, endorsement or vendor certification.</p></section><section className="article-section"><h2>Advisory work</h2><p>Paid blueprints are scoped recommendations. Clients receive assumptions, alternatives and a verification checklist. Stock, performance and future compatibility require their own evidence.</p></section></article>;
}
