import { planAll, NODE_CLASSES } from "./plan.mjs";

const HEADER = (title, hash, blurb) => [
  `# ${title}`,
  "",
  "Generated by `node scripts/compute/build.mjs` from `data/compute/*.json`. Do not edit by hand; edit the records and rerun.",
  `Data hash \`${hash}\`. Research date 2026-10-05. Buyer region assumed NL/EU (open).`,
  "",
  blurb,
  ""
];

const sourceMap = (data) => new Map(data.sources.map((s) => [s.id, s]));
const cite = (data, ids = []) => {
  const m = sourceMap(data);
  return ids.map((id) => (m.get(id) ? `[${id}](${m.get(id).url})${m.get(id).access === "snippet" ? " (snippet)" : ""}` : id)).join(", ");
};
const clip = (s, n = 600) => {
  const t = String(s ?? "").replace(/\s+/g, " ").trim();
  return t.length > n ? t.slice(0, n - 1) + "…" : t;
};
const esc = (s) => String(s ?? "").replace(/\|/g, "/");

export function renderCompanies(data, hash) {
  const L = HEADER("Company fundamentals: who stands behind each machine", hash, "What a founder can document about the business that sells the hardware: legal entity, EU presence, terms as written, support, review sentiment, firmware cadence and incidents. A `stub` has only snippet-level evidence. Inference is labelled in each evidence note.");
  const names = new Map(data.brands.map((b) => [b.id, b.name]));
  L.push("## At a glance", "");
  L.push("| Company | EU legal entity | EU VAT ID | Return and warranty as written | Trustpilot | Depth |");
  L.push("|---|---|---|---|---|---|");
  for (const c of data.fundamentals.companies) {
    const tp = c.trustpilot?.reviewCount != null ? `${c.trustpilot.score ?? "score withheld"} from ${c.trustpilot.reviewCount} (${c.trustpilot.observedOn})` : "not read";
    const eu = c.euLegalEntity === true ? "yes" : c.euLegalEntity === false ? "no" : "not established";
    const vat = c.euVatId?.value ? c.euVatId.value : c.euVatId?.status ?? "not found";
    L.push(`| ${names.get(c.brandId) ?? c.brandId} | ${eu} | ${esc(vat)} | ${esc(clip(c.euPresence?.returnAndWarrantyAsWritten || "not recorded", 200))} | ${esc(tp)} | ${c.depth} |`);
  }
  for (const c of data.fundamentals.companies) {
    L.push("", `## ${names.get(c.brandId) ?? c.brandId}${c.depth === "stub" ? " (stub)" : ""}`, "");
    if (c.depth === "stub") {
      L.push(clip(c.evidenceNotes), "", c.productBreadth ? `Known: ${clip(c.productBreadth)}` : "");
      continue;
    }
    L.push(`- Legal entities: ${c.legalEntities.map((e) => `${e.name} (${e.country}); ${clip(e.registrationEvidence, 220)}`).join("; ") || "not found"}`);
    L.push(`- Founded: ${clip(c.founded, 200)}. Headquarters: ${clip(c.hq, 120)}.`);
    L.push(`- Ownership and funding: ${clip(c.ownershipAndFunding, 420)}`);
    L.push(`- Scale: ${clip(c.scaleSignals, 320)}`);
    const noDot = (s, n) => clip(s, n).replace(/\.$/, "");
    L.push(`- EU presence: warehouses ${noDot(c.euPresence?.warehouses, 220)}; store entity ${noDot(c.euPresence?.euStoreEntity, 220)}; VAT or OSS ${noDot(c.euPresence?.vatOrOssHandling, 220)}`);
    L.push(`- Terms as written: ${clip(c.euPresence?.returnAndWarrantyAsWritten, 420)}`);
    L.push(`- Support: ${clip(c.support?.channels, 200)} Reputation evidence: ${clip(c.support?.reputationEvidence, 320)}`);
    L.push(`- Trustpilot: ${c.trustpilot?.reviewCount != null ? `${c.trustpilot.score ?? "score withheld"} from ${c.trustpilot.reviewCount} reviews, read ${c.trustpilot.observedOn}. ${clip(c.trustpilot.note, 260)}` : "not read"}`);
    L.push(`- Firmware and BIOS cadence: ${clip(c.firmwareAndBiosCadence, 300)}`);
    L.push(`- Longevity: ${clip(c.longevityEvidence, 260)}`);
    L.push(`- Pricing behavior: ${clip(c.pricingBehavior, 360)}`);
    if (c.incidents.length) L.push(`- Incidents and complaints: ${c.incidents.map((i) => `${clip(i.what, 240)} (${i.when || "date not stated"})`).join("; ")}`);
    if (c.businessRisks.length) L.push(`- Business risks: ${c.businessRisks.map((r) => clip(r, 240)).join("; ")}`);
    L.push(`- Evidence notes: ${clip(c.evidenceNotes, 420)}`);
    L.push(`- Sources: ${cite(data, c.sourceIds)}`);
  }
  L.push("", "## Open items", "");
  for (const g of data.fundamentals.gaps) L.push(`- ${clip(String(g).replace(/^OPEN:\s*/, ""), 260)}`);
  L.push("");
  return L.join("\n");
}

export function renderReviews(data, hash) {
  const L = HEADER("Independent reviews and owner reports", hash, "Reviews are labelled by who supplied the unit and whether the source was opened. A sponsored or maker-supplied unit is not an independent measurement, and snippet-only reviews carry no numbers here. Conflicting measurements are shown side by side.");
  const byKey = new Map();
  for (const r of data.reviews.reviews) { if (!byKey.has(r.machineKey)) byKey.set(r.machineKey, []); byKey.get(r.machineKey).push(r); }
  const sm = sourceMap(data);
  for (const [key, list] of byKey) {
    const c = data.reviews.consensus[key];
    L.push(`## ${key}`, "");
    if (c) L.push(clip(c.summary, 900), "");
    L.push("| Outlet | Date | Unit | Independent | Verdict | Measured |");
    L.push("|---|---|---|---|---|---|");
    for (const r of list) {
      const m = r.measured ?? {};
      const bits = [];
      if (m.idleWatts != null) bits.push(`idle ${m.idleWatts} W`);
      if (m.loadWatts != null) bits.push(`load ${m.loadWatts} W`);
      if (m.noiseDbA != null) bits.push(`${m.noiseDbA} dBA`);
      for (const t of m.tokensPerSecond ?? []) bits.push(`${t.model} ${t.quant ?? ""} ${t.value} tok/s${t.os ? " (" + t.os + ")" : ""}`.replace(/\s+/g, " "));
      if (m.thermalNotes) bits.push(clip(m.thermalNotes, 100));
      const url = sm.get(r.sourceId)?.url;
      L.push(`| ${url ? `[${esc(r.outlet)}](${url})` : esc(r.outlet)}${r.snippetOnly ? " (snippet)" : ""} | ${r.publishedAt || "not stated"} | ${r.unitSource}${r.sponsored ? ", sponsored" : ""} | ${r.independent ? "yes" : "no"} | ${esc(clip(r.verdict, 260))} | ${esc(bits.join("; ") || "none")} |`);
    }
    const issues = list.flatMap((r) => r.issuesFound ?? []);
    if (issues.length) L.push("", `Issues found: ${[...new Set(issues)].map((i) => clip(i, 160)).join("; ")}`);
    L.push("");
  }
  L.push("## Owner reports", "", "| Machine | Platform | Severity | Resolved | Issue |", "|---|---|---|---|---|");
  for (const o of data.reviews.ownerReports) L.push(`| ${o.machineKey} | ${o.platform} | ${o.severity} | ${o.resolved} | ${esc(clip(o.issue, 260))} |`);
  L.push("", "## Open items", "");
  for (const g of data.reviews.gaps) L.push(`- ${clip(String(g).replace(/^OPEN:\s*/, ""), 260)}`);
  L.push("");
  return L.join("\n");
}

export function renderVerification(data, hash) {
  const L = HEADER("Verification log", hash, "Every statement an earlier research pass flagged as not verified, and what a second pass found. Statuses: verified, partially-verified, refuted, unverifiable. A statement counts as verified only with an opened source.");
  const counts = {};
  for (const i of data.verification.items) counts[i.status] = (counts[i.status] ?? 0) + 1;
  L.push(`Items: ${data.verification.items.length} (${Object.entries(counts).map(([k, v]) => `${v} ${k}`).join(", ")}). Gaps still open: ${data.gaps.filter((g) => g.status === "open").length} of ${data.gaps.length}.`, "");
  L.push("## What was unverified, and where it stands", "", "| Was | Status | Now |", "|---|---|---|");
  for (const p of data.verification.programme) L.push(`| ${esc(p.was)} | ${p.status} | ${esc(clip(p.now, 420))} |`);
  for (const area of ["technical", "legal"]) {
    L.push("", `## ${area === "technical" ? "Technical items" : "Legal, customs and disclosure items"}`);
    for (const i of data.verification.items.filter((x) => x.area === area)) {
      L.push("", `### ${i.id}: ${clip(i.question, 160)}`, "", `Status: ${i.status}.`, "", clip(i.finding, 900));
      if (i.caveat) L.push("", `Caveat: ${clip(i.caveat, 520)}`);
      L.push("", `Sources: ${cite(data, i.sourceIds)}`);
    }
  }
  L.push("", "## Gap status", "", "| Status | Count |", "|---|---|");
  for (const s of ["open", "partial", "closed"]) L.push(`| ${s} | ${data.gaps.filter((g) => g.status === s).length} |`);
  L.push("");
  return L.join("\n");
}

export function renderExpansion(data, hash) {
  const e = data.expansion;
  const L = HEADER("Growing past one box: eGPU, clusters, racks and RAG", hash, "What the evidence says about scaling a Strix Halo mini PC. Figures marked secondary come from blogs or forums; none was measured by us.");
  L.push("## External GPU", "", "| Link | Lanes | Theoretical GB/s | Measured notes | Sources |", "|---|---|---|---|---|");
  for (const l of e.egpu.links ?? []) L.push(`| ${esc(l.name)} | ${esc(l.lanes)} | ${l.theoreticalGBs ?? "n/v"} | ${esc(clip(l.measuredNotes, 240))} | ${cite(data, l.sourceIds)} |`);
  if ((e.egpu.strixHaloResults ?? []).length) {
    L.push("", "Results on Strix Halo or similar:", "");
    for (const r of e.egpu.strixHaloResults) L.push(`- ${clip(r.setup, 160)}: ${clip(r.workload, 120)}. ${clip(r.result, 260)} (${r.os || "OS not stated"}). ${cite(data, r.sourceIds)}`);
  }
  if ((e.egpu.docksAndAdapters ?? []).length) {
    L.push("", "Docks and adapters:", "");
    for (const d of e.egpu.docksAndAdapters) L.push(`- ${d.name}: ${d.priceEur != null ? `EUR ${d.priceEur}` : "price not verified"}${d.merchant ? `, ${d.merchant}` : ""}${d.observedOn ? `, read ${d.observedOn}` : ""}. ${clip(d.notes, 180)}`);
  }
  L.push("", `Limits: ${(e.egpu.limits ?? []).map((x) => clip(x, 200)).join("; ")}`, "", `When it helps: ${clip(e.egpu.whenItHelps, 400)}`, "", `When it does not: ${clip(e.egpu.whenItDoesNot, 400)}`);
  L.push("", "## Clustering mini PCs", "");
  for (const a of e.clustering.approaches ?? []) {
    L.push(`### ${a.name}`, "", `${clip(a.what, 360)} Network needs: ${clip(a.networkNeeds, 240)}. Maturity: ${clip(a.maturity, 240)}. Windows: ${clip(a.windowsSupport, 200)}.`);
    for (const m of a.measured ?? []) L.push(`- ${clip(m.setup, 160)}, ${clip(m.model, 80)}: ${clip(m.result, 200)}`);
    L.push(`Sources: ${cite(data, a.sourceIds)}`, "");
  }
  L.push("Networking:", "");
  for (const n of e.clustering.networking ?? []) L.push(`- ${n.option}: ${n.bandwidthGbps ?? "n/v"} Gbps. ${clip(n.measuredNotes, 240)} ${cite(data, n.sourceIds)}`);
  L.push("", `Limits: ${(e.clustering.limits ?? []).map((x) => clip(x, 220)).join("; ")}`);
  L.push("", "## Racks", "");
  for (const o of e.racks.options ?? []) L.push(`- ${o.name}: ${clip(o.what, 200)}${o.priceEur != null ? `, EUR ${o.priceEur}` : ""}. ${cite(data, o.sourceIds)}`);
  for (const n of e.racks.notes ?? []) L.push(`- ${clip(n, 240)}`);
  L.push("", "## RAG on these machines", "", "| Component | Example | Memory GB | Basis |", "|---|---|---|---|");
  for (const f of e.rag.footprints ?? []) L.push(`| ${esc(f.component)} | ${esc(clip(f.example, 120))} | ${f.memoryGb ?? "n/v"} | ${f.basis} |`);
  L.push("", clip(e.rag.fitOnStrixHalo, 600));
  for (const n of e.rag.notes ?? []) L.push("", `- ${clip(n, 320)}`);
  L.push("", "## Scale up versus scale out", "");
  for (const f of e.scaleUpVsScaleOut.findings ?? []) L.push(`- ${clip(f, 360)}`);
  L.push("", `Sources: ${cite(data, e.scaleUpVsScaleOut.sourceIds)}`, "", "## Open items", "");
  for (const g of e.gaps ?? []) L.push(`- ${clip(String(g).replace(/^OPEN:\s*/, ""), 260)}`);
  L.push("");
  return L.join("\n");
}


export function renderStackPlan(data, hash) {
  const L = HEADER("Stack planner: memory, VRAM and nodes for each stage", hash, "Resource totals for four stages of growth, from the constants in `workload-model.json` and the scenarios in `scenarios.json`. Each line says whether its basis is documented, measured, derived or an estimate. The estimates dominate; replace them with a node's own heartbeat data after a week. Fit means memory capacity only: speed, thermals and software support are separate (see the other documents).");
  const money = (p) => (p ? `EUR ${p.amount.toLocaleString("en-US", { maximumFractionDigits: 2 })} (${p.model}, ${p.tax})` : "no page-read price");
  for (const p of planAll(data)) {
    L.push(`## ${p.name}`, "", p.description, "");
    L.push("| Item | Count | Low GB | High GB | Basis |", "|---|---|---|---|---|");
    for (const l of p.lines) L.push(`| ${l.item} | ${l.count} | ${l.low} | ${l.high} | ${l.basis} |`);
    L.push(`| Operating system and services | 1 | ${p.osAndServices} | ${p.osAndServices} | measured |`, `| Free-RAM floor | 1 | ${p.floorGb} | ${p.floorGb} | policy |`);
    L.push("", `One node needs ${p.oneNode.low} to ${p.oneNode.high} GB including the floor.`, "");
    L.push("| Memory class | Fits at the low estimate | Fits at the high estimate | Cheapest page-read system | Cheapest with 256 GB/s or more (model-capable) |", "|---|---|---|---|---|");
    for (const f of p.fits) L.push(`| ${f.classGb} GB | ${f.fitsLow ? "yes" : "no"} | ${f.fitsHigh ? "yes" : "no"} | ${money(f.cheapestPageRead)} | ${money(f.cheapestModelCapable)} |`);
    if (p.split) {
      L.push("", `Two nodes: agents and business apps need ${p.split.nodeA.low}-${p.split.nodeA.high} GB (${p.split.nodeA.classGb ?? "more than 192"} GB class); the model and RAG node needs ${p.split.nodeB.low}-${p.split.nodeB.high} GB (${p.split.nodeB.classGb ?? "more than 192"} GB class). Cheapest page-read for the agent node: ${money(p.split.nodeA.cheapestPageRead)}. Cheapest model-capable (256 GB/s or more) for the model node: ${money(p.split.nodeB.cheapestPageRead)}.`);
    }
    if (p.gpu.jobs.length) {
      L.push("", "GPU queue (jobs run one at a time, so the card must hold the largest):", "");
      for (const j of p.gpu.jobs) L.push(`- ${j.name}: ${j.gb} GB (${j.basis})`);
      L.push("", `Required VRAM: ${p.gpu.vramRequired} GB, which points to a ${p.gpu.tier}.`);
      if (p.gpu.candidates.length) L.push("", "Cards with enough VRAM in the research (EU prices are unverified unless stated):", "", ...p.gpu.candidates.map((g) => `- ${g.id}: ${g.vramGb} GB, ${g.bandwidthGBs ?? "bandwidth not found"} GB/s, ${g.tdpWatts ?? "TGP not found"} W, EU price verified: ${g.euPriceVerified ? "yes" : "no"}`));
    }
    L.push("");
  }
  L.push("## Reading these numbers", "", "- Unified-memory machines share one pool between the system and the model, so system and model memory add up.", "- A memory class that fits only at the low estimate is a risk, not a plan.", "- Langfuse's documented 16 GiB is the largest single line; running it on another small node or using a hosted option changes the result.", "- GPU jobs are sized by VRAM only. A card that fits a job can still be slow.", "- Estimates come from one profile of a laptop and must be replaced by the node's own measurements.", "");
  return L.join("\n");
}

export const EXTRA_DOCS = [
  ["COMPANY-FUNDAMENTALS.md", renderCompanies],
  ["REVIEWS.md", renderReviews],
  ["VERIFICATION-LOG.md", renderVerification],
  ["EXPANSION-PATHS.md", renderExpansion],
  ["STACK-PLANNER.md", renderStackPlan]
];
