-- Starlight Agentic Engine durable control plane.
-- Review and apply to the existing EU "Starlight Platform" Supabase project.
-- All tables are server-mediated in P1/P2; no anon/authenticated direct access.

create table if not exists public.agent_mandates (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  principal_id uuid references public.principals(id) on delete set null,
  name text not null check (length(trim(name)) > 0),
  status text not null default 'active' check (status in ('draft','active','suspended','revoked','expired')),
  allowed_authorities text[] not null default array['observe','research','draft']::text[],
  allowed_tools text[] not null default '{}'::text[],
  denied_tools text[] not null default '{}'::text[],
  max_run_cost_eur numeric(12,4) not null default 5 check (max_run_cost_eur >= 0),
  max_external_spend_eur numeric(14,2) not null default 0 check (max_external_spend_eur >= 0),
  max_tokens bigint not null default 250000 check (max_tokens > 0),
  policy jsonb not null default '{}'::jsonb check (jsonb_typeof(policy) = 'object'),
  starts_at timestamptz not null default now(),
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (expires_at is null or expires_at > starts_at)
);

create index if not exists agent_mandates_tenant_status_idx on public.agent_mandates(tenant_id, status);
create index if not exists agent_mandates_principal_idx on public.agent_mandates(principal_id) where principal_id is not null;

create table if not exists public.agent_control_runs (
  run_id text primary key,
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  principal_id uuid references public.principals(id) on delete set null,
  mandate_id uuid references public.agent_mandates(id) on delete set null,
  parent_run_id text references public.agent_control_runs(run_id) on delete set null,
  objective text not null check (length(trim(objective)) > 0),
  workload text not null check (workload in ('procurement','research','architecture','software','creative','operations','exchange')),
  risk text not null check (risk in ('low','medium','high','critical')),
  orchestration_pattern text not null check (orchestration_pattern in ('direct','sequential','parallel','iterative','cascade','broadcast')),
  status text not null default 'planned' check (status in ('planned','running','approval_required','completed','failed','aborted')),
  token_budget bigint not null check (token_budget > 0),
  cost_budget_eur numeric(12,4) not null check (cost_budget_eur >= 0),
  external_spend_budget_eur numeric(14,2) not null default 0 check (external_spend_budget_eur >= 0),
  tokens_used bigint not null default 0 check (tokens_used >= 0),
  model_cost_eur numeric(12,4) not null default 0 check (model_cost_eur >= 0),
  external_spend_eur numeric(14,2) not null default 0 check (external_spend_eur >= 0),
  request jsonb not null check (jsonb_typeof(request) = 'object'),
  plan jsonb not null check (jsonb_typeof(plan) = 'object'),
  result jsonb,
  failure jsonb,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists agent_control_runs_tenant_created_idx on public.agent_control_runs(tenant_id, created_at desc);
create index if not exists agent_control_runs_status_idx on public.agent_control_runs(status, created_at desc);
create index if not exists agent_control_runs_parent_idx on public.agent_control_runs(parent_run_id) where parent_run_id is not null;

create table if not exists public.agent_run_events (
  id bigint generated by default as identity primary key,
  run_id text not null references public.agent_control_runs(run_id) on delete cascade,
  step_id text,
  event_type text not null,
  actor text not null,
  model text,
  tool text,
  input_tokens bigint check (input_tokens is null or input_tokens >= 0),
  output_tokens bigint check (output_tokens is null or output_tokens >= 0),
  cost_eur numeric(12,6) check (cost_eur is null or cost_eur >= 0),
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now()
);

create index if not exists agent_run_events_run_id_idx on public.agent_run_events(run_id, id);
create index if not exists agent_run_events_created_idx on public.agent_run_events(created_at desc);

create table if not exists public.agent_approvals (
  id uuid primary key default gen_random_uuid(),
  run_id text not null references public.agent_control_runs(run_id) on delete cascade,
  step_id text not null,
  authority text not null check (authority in ('external-write','purchase','settlement','deploy')),
  principal_id uuid not null references public.principals(id) on delete restrict,
  status text not null default 'pending' check (status in ('pending','approved','rejected','expired','revoked')),
  reason text,
  approval_context jsonb not null default '{}'::jsonb check (jsonb_typeof(approval_context) = 'object'),
  expires_at timestamptz,
  decided_at timestamptz,
  created_at timestamptz not null default now(),
  unique(run_id, step_id, authority, principal_id)
);

create index if not exists agent_approvals_run_status_idx on public.agent_approvals(run_id, status);

create table if not exists public.agent_memories (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  principal_id uuid references public.principals(id) on delete cascade,
  agent_id text,
  memory_kind text not null check (memory_kind in ('working','episodic','semantic','policy')),
  memory_key text not null check (length(trim(memory_key)) > 0),
  value jsonb not null,
  provenance jsonb not null default '{}'::jsonb check (jsonb_typeof(provenance) = 'object'),
  confidence real check (confidence is null or (confidence >= 0 and confidence <= 1)),
  valid_from timestamptz not null default now(),
  valid_until timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique nulls not distinct (tenant_id, principal_id, agent_id, memory_kind, memory_key),
  check (valid_until is null or valid_until > valid_from)
);

create index if not exists agent_memories_tenant_kind_idx on public.agent_memories(tenant_id, memory_kind, updated_at desc);
create index if not exists agent_memories_principal_idx on public.agent_memories(principal_id) where principal_id is not null;

alter table public.agent_mandates enable row level security;
alter table public.agent_control_runs enable row level security;
alter table public.agent_run_events enable row level security;
alter table public.agent_approvals enable row level security;
alter table public.agent_memories enable row level security;

drop policy if exists agent_mandates_service_role_only on public.agent_mandates;
create policy agent_mandates_service_role_only on public.agent_mandates for all to service_role using (true) with check (true);

drop policy if exists agent_control_runs_service_role_only on public.agent_control_runs;
create policy agent_control_runs_service_role_only on public.agent_control_runs for all to service_role using (true) with check (true);

drop policy if exists agent_run_events_service_role_only on public.agent_run_events;
create policy agent_run_events_service_role_only on public.agent_run_events for all to service_role using (true) with check (true);

drop policy if exists agent_approvals_service_role_only on public.agent_approvals;
create policy agent_approvals_service_role_only on public.agent_approvals for all to service_role using (true) with check (true);

drop policy if exists agent_memories_service_role_only on public.agent_memories;
create policy agent_memories_service_role_only on public.agent_memories for all to service_role using (true) with check (true);

comment on table public.agent_mandates is 'Server-mediated authority, tool and spend envelopes for Starlight agents.';
comment on table public.agent_control_runs is 'Durable tenant-scoped agent run state, immutable request contract and economic budget ledger.';
comment on table public.agent_run_events is 'Append-oriented execution receipts for governed agent runs.';
comment on table public.agent_approvals is 'Human approval decisions for consequential agent steps.';
comment on table public.agent_memories is 'Tenant-scoped working, episodic, semantic and policy memory records; vectors are secondary indexes only.';
